stages:
 - build
 - deploy

import_data:
  stage: build
  script:
   - apk add --no-cache bash git curl 
   - 'curl --header "Authorization header: Bearer: $TOKEN" "http://gitlab.example.com/api/v4/projects/498/jobs/artifacts/main/download?job=generate_template" -o artifacts.zip'
   - unzip artifacts.zip
  artifacts:
   paths:
    - data.json

create_s3:
  stage: deploy
  script: 
   - apk add --no-cache bash python3 py3-pip
   - echo $S3_BUCKETS
   - python3 s3.py
