stages:
 - build
 - deploy

services:
  - name: hashicorp/vault
    alias: vault

import_data:
  stage: build
  script:
   - apk add --no-cache bash git curl 
   - 'curl --header "Authorization header: Bearer: $TOKEN" "http://gitlab.example.com/api/v4/projects/498/jobs/artifacts/main/download?job=generate_template" -o artifacts.zip'
   - unzip artifacts.zip
  artifacts:
   paths:
    - data.json
    - .env

create_s3:
  stage: deploy
  variables:
    VAULT_ADDR: http://vault:8200
    VAULT_TOKEN: root
  script: 
    - ./scripts/s3.sh
  needs:
    - job: import_data

