stages:
 - build
 - deploy

import_data:
  stage: build
  script:
   - apk add --no-cache bash git curl 
   - 'curl --header "Authorization header: Bearer: $TOKEN" "http://gitlab.example.com/api/v4/projects/498/jobs/artifacts/main/download?job=generate_template" -o artifacts.zip'
   - unzip artifacts.zip
  artifacts:
   paths:
    - data.json
    - .env

create_s3:
  stage: deploy
  script: 
   - apk add --no-cache bash python3 py3-pip
   - pip3 install hvac
   - set -a 
   - ENV=.env
   - source $ENV
   - set +a
   - python3 s3.py
  needs:
    - job: import_data
      artifacts: true

